### ISSUE TITLE
Request for info on MDI

### ISSUE THREAD

**Issue by RoBeDi** [harborsiem/WindowsRibbon#10] opened 2022-11-16 10:49 UTC
Hi,

I am trying to develop a MDI application, using your WindowsRibbon wrapper. But I've noticed that the Ribbon menu is not acting fluently as within a single form. When starting the project and after minimizing the Ribbon, you can see the **minimize**, **maximize** and **close** button on top of the **minimize** button of the Ribbon menu. It disappears when you hover over them with your mouse. The same is displayed with the tab pages. Also the MDI Child appears not completely maximized when starting the application.

**Minimized Ribbon from**
![image](https://user-images.githubusercontent.com/63212787/202226770-291959af-d167-4a63-876c-38e655693d67.png)

**When hovering over the Tabs and buttons**
![image](https://user-images.githubusercontent.com/63212787/202227065-2206cc25-bbbc-494b-bb4f-a2c7dece040f.png)
![image](https://user-images.githubusercontent.com/63212787/202227220-8385b735-2bea-4160-b99d-b1810936e45f.png)

Additionally, when the application is not in focus, then it appears like this:
![image](https://user-images.githubusercontent.com/63212787/202227504-cd8743b7-6656-4618-ac88-a6f4d0eed489.png)

I am using the simple approach in the code (MDI Parent):
`
        private void frmMain_Load(object sender, EventArgs e)
        {
            frmWorkSpaceA newMDIChild = new frmWorkSpaceA();
            newMDIChild.MdiParent = this;
            newMDIChild.WindowState = FormWindowState.Maximized;
            newMDIChild.Show();
        }
`
_PS: I am not at my computer, but will upload some screenshots later today._

PPS: AWESOME wrapper :)
with regards,
Roland

**Comment by harborsiem** [comment] 2022-11-17 10:02
Hi Roland,
I think the problem is the code
`
newMDIChild.WindowState = FormWindowState.Maximized;
`
You should use this code instead
`
            Size s = new Size(this.ClientSize.Width - 8, this.ClientSize.Height - _ribbon.Height - 8);
            newMDIChild.Size = s;
`
Your MDI Child should not have a Maximimized Button

Regards
Hartmut

**Comment by RoBeDi** [comment] 2022-11-17 18:56
Hi,

Thanks for coming back to me. Using your code did improve a little, but when clicking on Home tab page it appeared again. 
![image](https://user-images.githubusercontent.com/63212787/202517351-3e967fe4-2548-4158-b205-300767d4b387.png)

When resizing the ribbon, the issue disappeared. But came back after clicking any of the tab pages.

Behavior:

1. Once project started, no visible issues
2. Dragging the form, the issue appears
3. Clicking between the second and third tab page will resolve the view, but clicking File makes the issue comes back
4. Minimizing and maximizing the ribbon will solve the issue as well

Weird thing is that it only occurs whenever I click the File tab page.

**Comment by RoBeDi** [comment] 2022-11-18 19:20
Hi again,

I reproduced the steps exactly as you suggested and yes, no issues... But... but, but, but...

How can I make the MDI child maximized upon load?

**Comment by harborsiem** [comment] 2022-11-19 09:48
Mdi is not supported by the Ribbon directly. see: [Mdi support](https://social.msdn.microsoft.com/Forums/SqlServer/en-US/aacd529d-e17b-47c7-84c2-d7d1f1bd4b6a/mdi-support-in-windows-ribbon-framework?forum=windowsribbondevelopment).
This is the answer of a Microsoft member.
But you can calculate a size for the MDI client without maximizing every time when the main form changes the size.
Or you don't use Mdi. Alternatively, you can use a TabControl with some effort for closing, hiding, ....

**Comment by RoBeDi** [comment] 2022-11-19 19:57
Shame, but ok... will use that instead... Thanks anyway for trying.

**Comment by harborsiem** [comment] 2022-11-20 12:19
I have updated the Wiki (News and Hints) with some words for MDI support

**Closed by harborsiem** 2022-11-20 12:19 UTC
